# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Faq

# Model Form Field configuration
form: $/anguro/capse/models/faq/fields.yaml

# Model Class name
modelClass: Anguro\Capse\Models\Faq

# Default redirect location
defaultRedirect: anguro/capse/faqs

# Create page
create:
    title: Nueva Pregunta
    redirect: anguro/capse/faqs/update/:id
    redirectClose: anguro/capse/faqs

# Update page
update:
    title: Editar Pregunta
    redirect: anguro/capse/faqs
    redirectClose: anguro/capse/faqs

# Preview page
preview:
    title: Vista Previa Faq
