# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    cuando:

        # Filter name
        label: anguro.capse::lang.eventos.filter_date

        # Filter type
        type: daterange

        # SQL Conditions
        conditions: cuando >= ':after' AND cuando <= ':before'
